#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/rlidwka/sinopia/tree/master/conf
#
# docker run --name verdaccio -d -v /data/verdaccio/conf:/verdaccio/conf  -v /data/verdaccio/storage:/verdaccio/storage  -p 4873:4873 verdaccio/verdaccio:4
# docker run --name verdaccio -d -v /Users/maccintoshhd/verdaccio/conf:/verdaccio/conf  -v /Users/maccintoshhd/verdaccio/storage:/verdaccio/storage -v /Users/maccintoshhd/verdaccio/plugins:/verdaccio/plugins -p 4873:4873 verdaccio/verdaccio:5
# path to a directory with all packages
storage: ../storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 20

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: sinopia.log, level: info}

listen:
  - 0.0.0.0:4873